export const styles = {
  container: {
    minHeight: "100vh",
    backgroundColor: "#f8fafb",
    padding: { xs: "20px 16px", md: "40px 60px" },
    fontFamily: "Inter, sans-serif",
  },
  header: {
    marginBottom: "40px",
  },
  title: {
    fontSize: { xs: "28px", md: "32px" },
    fontWeight: 600,
    color: "#1a1a1a",
    marginBottom: "8px",
    fontFamily: "Inter, sans-serif",
  },
  subtitle: {
    fontSize: "14px",
    color: "#6b7280",
    fontFamily: "Inter, sans-serif",
  },
  statsGrid: {
    display: "grid",
    gridTemplateColumns: {
      xs: "1fr",
      sm: "repeat(2, 1fr)",
      lg: "repeat(4, 1fr)",
    },
    gap: "20px",
    marginBottom: "30px",
  },
  statCard: {
    backgroundColor: "#ffffff",
    borderRadius: "12px",
    padding: "24px",
    boxShadow: "0 1px 3px rgba(0, 0, 0, 0.05)",
    position: "relative",
    transition: "transform 0.2s, box-shadow 0.2s",
    "&:hover": {
      transform: "translateY(-2px)",
      boxShadow: "0 4px 12px rgba(0, 0, 0, 0.08)",
    },
  },
  statIcon: {
    width: "40px",
    height: "40px",
    borderRadius: "10px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: "16px",
  },
  statValue: {
    fontSize: "32px",
    fontWeight: 700,
    color: "#1a1a1a",
    marginBottom: "4px",
    fontFamily: "Inter, sans-serif",
  },
  statLabel: {
    fontSize: "13px",
    color: "#6b7280",
    fontFamily: "Inter, sans-serif",
  },
  badge: {
    position: "absolute",
    top: "20px",
    right: "20px",
    fontSize: "12px",
    fontWeight: 600,
    padding: "4px 8px",
    borderRadius: "6px",
  },
  chartsRow: {
    display: "grid",
    gridTemplateColumns: { xs: "1fr", lg: "2fr 1fr" },
    gap: "20px",
    marginBottom: "30px",
  },
  chartCard: {
    backgroundColor: "#ffffff",
    borderRadius: "12px",
    padding: "28px",
    boxShadow: "0 1px 3px rgba(0, 0, 0, 0.05)",
  },
  chartTitle: {
    fontSize: "16px",
    fontWeight: 600,
    color: "#1a1a1a",
    marginBottom: "8px",
    fontFamily: "Inter, sans-serif",
  },
  chartSubtitle: {
    fontSize: "12px",
    color: "#9ca3af",
    marginBottom: "20px",
    fontFamily: "Inter, sans-serif",
  },
  barChartCard: {
    backgroundColor: "#ffffff",
    borderRadius: "12px",
    padding: "28px",
    boxShadow: "0 1px 3px rgba(0, 0, 0, 0.05)",
    marginBottom: "30px",
  },
  bottomRow: {
    display: "grid",
    gridTemplateColumns: { xs: "1fr", lg: "1fr 1fr" },
    gap: "20px",
    marginBottom: "30px",
  },
  activityCard: {
    backgroundColor: "#ffffff",
    borderRadius: "12px",
    padding: "28px",
    boxShadow: "0 1px 3px rgba(0, 0, 0, 0.05)",
  },
  activityItem: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "16px 0",
    borderBottom: "1px solid #f3f4f6",
    "&:last-child": {
      borderBottom: "none",
    },
  },
  activityInfo: {
    flex: 1,
  },
  activityLocation: {
    fontSize: "14px",
    fontWeight: 500,
    color: "#1a1a1a",
    marginBottom: "4px",
    fontFamily: "Inter, sans-serif",
  },
  activityDate: {
    fontSize: "12px",
    color: "#9ca3af",
    fontFamily: "Inter, sans-serif",
  },
  activityBadge: {
    backgroundColor: "#e0f2fe",
    color: "#0284c7",
    fontSize: "12px",
    fontWeight: 600,
    padding: "6px 12px",
    borderRadius: "6px",
    marginLeft: "12px",
    fontFamily: "Inter, sans-serif",
  },
  contributorItem: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "16px 0",
    borderBottom: "1px solid #f3f4f6",
    "&:last-child": {
      borderBottom: "none",
    },
  },
  contributorLeft: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
  },
  contributorAvatar: {
    width: "44px",
    height: "44px",
    borderRadius: "50%",
    backgroundColor: "#e0f2fe",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: "#0284c7",
  },
  contributorName: {
    fontSize: "14px",
    fontWeight: 500,
    color: "#1a1a1a",
    marginBottom: "4px",
    fontFamily: "Inter, sans-serif",
  },
  contributorCount: {
    fontSize: "12px",
    color: "#9ca3af",
    fontFamily: "Inter, sans-serif",
  },
  contributorRank: {
    fontSize: "18px",
    fontWeight: 600,
    color: "#9ca3af",
    fontFamily: "Inter, sans-serif",
  },
  youBadge: {
    backgroundColor: "#0ea5e9",
    color: "#ffffff",
    fontSize: "10px",
    fontWeight: 600,
    padding: "2px 8px",
    borderRadius: "4px",
    marginLeft: "6px",
    fontFamily: "Inter, sans-serif",
  },
  communityCard: {
    backgroundColor: "#ffffff",
    borderRadius: "12px",
    padding: "28px",
    boxShadow: "0 1px 3px rgba(0, 0, 0, 0.05)",
  },
  communityTitle: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    fontSize: "16px",
    fontWeight: 600,
    color: "#1a1a1a",
    marginBottom: "24px",
    fontFamily: "Inter, sans-serif",
  },
  communityStats: {
    display: "grid",
    gridTemplateColumns: { xs: "1fr", sm: "repeat(3, 1fr)" },
    gap: "24px",
  },
  communityStat: {
    textAlign: { xs: "left", sm: "center" },
  },
  communityValue: {
    fontSize: "28px",
    fontWeight: 700,
    color: "#0ea5e9",
    marginBottom: "4px",
    fontFamily: "Inter, sans-serif",
  },
  communityLabel: {
    fontSize: "12px",
    color: "#6b7280",
    fontFamily: "Inter, sans-serif",
  },
};
